name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # using npx to avoid needing to install deno

      # --dry-run is used to avoid publishing the
      # module until we can figure out how to handle
      # the jsr.io publishing with the @gamebridge account admin.

      # When we decide to publish to JSR we'll need to rename the
      # module to @gamebridge/serialize or something similar
      # because `_` is not allowed in module names.
      - run: npx jsr publish --dry-run
