# Copyright 2018-2021 Gamebridge.ai authors. All rights reserved. MIT license.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  deno_v1:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        deno: [v1.x]
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: Deno test
        run: deno test --no-lock

  deno_v2_and_up:
    runs-on: ${{ matrix.os }}

    needs: deno_v1

    strategy:
      matrix:
        deno: [v2.x]
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: Deno lint
        run: deno task lint

      - name: Deno format check
        run: deno task fmt --check
        if: matrix.os != 'windows-latest'

      - name: Deno test
        run: deno task test:coverage

      - name: Generate coverage report
        run: deno task test:coverage:report

      - name: Coverage report
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: ./coverage/lcov.info
          min_coverage: 100

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Build and test NPM module
        run: deno task build
        if: matrix.os == 'ubuntu-latest'
